/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HealthConfig } from './HealthConfig';

/**
* It should hold only portable information about the container. Here, \"portable\" means \"independent from the host we are running on\". Non-portable information *should* appear in HostConfig. All fields added to this struct must be marked `omitempty` to keep getting predictable hashes from the old `v1Compatibility` configuration.
*/
export class Config {
    'argsEscaped'?: boolean;
    'attachStderr'?: boolean;
    'attachStdin'?: boolean;
    'attachStdout'?: boolean;
    /**
    * We need to override the json decoder to accept both options.
    */
    'cmd'?: Array<string>;
    'domainname'?: string;
    /**
    * We need to override the json decoder to accept both options.
    */
    'entrypoint'?: Array<string>;
    'env'?: Array<string>;
    /**
    * PortSet is a collection of structs indexed by Port
    */
    'exposedPorts'?: { [key: string]: any; };
    'healthcheck'?: HealthConfig;
    'hostname'?: string;
    'image'?: string;
    'labels'?: { [key: string]: string; };
    'macAddress'?: string;
    'networkDisabled'?: boolean;
    'onBuild'?: Array<string>;
    'openStdin'?: boolean;
    /**
    * We need to override the json decoder to accept both options.
    */
    'shell'?: Array<string>;
    'stdinOnce'?: boolean;
    'stopSignal'?: string;
    'stopTimeout'?: number;
    'tty'?: boolean;
    'user'?: string;
    'volumes'?: { [key: string]: any; };
    'workingDir'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'argsEscaped',
            'baseName': 'ArgsEscaped',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'attachStderr',
            'baseName': 'AttachStderr',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'attachStdin',
            'baseName': 'AttachStdin',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'attachStdout',
            'baseName': 'AttachStdout',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'cmd',
            'baseName': 'Cmd',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'domainname',
            'baseName': 'Domainname',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'entrypoint',
            'baseName': 'Entrypoint',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'env',
            'baseName': 'Env',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'exposedPorts',
            'baseName': 'ExposedPorts',
            'type': '{ [key: string]: any; }',
            'format': '',
        },
        {
            'name': 'healthcheck',
            'baseName': 'Healthcheck',
            'type': 'HealthConfig',
            'format': '',
        },
        {
            'name': 'hostname',
            'baseName': 'Hostname',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'image',
            'baseName': 'Image',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'labels',
            'baseName': 'Labels',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'macAddress',
            'baseName': 'MacAddress',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'networkDisabled',
            'baseName': 'NetworkDisabled',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'onBuild',
            'baseName': 'OnBuild',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'openStdin',
            'baseName': 'OpenStdin',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'shell',
            'baseName': 'Shell',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'stdinOnce',
            'baseName': 'StdinOnce',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'stopSignal',
            'baseName': 'StopSignal',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'stopTimeout',
            'baseName': 'StopTimeout',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'tty',
            'baseName': 'Tty',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'user',
            'baseName': 'User',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'volumes',
            'baseName': 'Volumes',
            'type': '{ [key: string]: any; }',
            'format': '',
        },
        {
            'name': 'workingDir',
            'baseName': 'WorkingDir',
            'type': 'string',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return Config.attributeTypeMap;
    }

    public constructor() {
    }
}

