/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ContainerExecRequest {
    /**
    * Attach to stderr of the exec command
    */
    'attachStderr'?: boolean;
    /**
    * Attach to stdin of the exec command
    */
    'attachStdin'?: boolean;
    /**
    * Attach to stdout of the exec command
    */
    'attachStdout'?: boolean;
    /**
    * Command to run, as a string or array of strings.
    */
    'cmd'?: Array<string>;
    /**
    * \"Override the key sequence for detaching a container. Format is a single character [a-Z] or ctrl-<value> where <value> is one of: a-z, @, ^, [, , or _.\" 
    */
    'detachKeys'?: string;
    /**
    * A list of environment variables in the form [\"VAR=value\", ...]
    */
    'env'?: Array<string>;
    /**
    * Runs the exec process with extended privileges
    */
    'privileged'?: boolean;
    /**
    * Allocate a pseudo-TTY
    */
    'tty'?: boolean;
    /**
    * \"The user, and optionally, group to run the exec process inside the container. Format is one of: user, user:group, uid, or uid:gid.\" 
    */
    'user'?: string;
    /**
    * The working directory for the exec process inside the container.
    */
    'workingDir'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'attachStderr',
            'baseName': 'AttachStderr',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'attachStdin',
            'baseName': 'AttachStdin',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'attachStdout',
            'baseName': 'AttachStdout',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'cmd',
            'baseName': 'Cmd',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'detachKeys',
            'baseName': 'DetachKeys',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'env',
            'baseName': 'Env',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'privileged',
            'baseName': 'Privileged',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'tty',
            'baseName': 'Tty',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'user',
            'baseName': 'User',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'workingDir',
            'baseName': 'WorkingDir',
            'type': 'string',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return ContainerExecRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

