/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LinuxResources } from './LinuxResources';
import type { LinuxThrottleDevice } from './LinuxThrottleDevice';
import type { LinuxWeightDevice } from './LinuxWeightDevice';
import type { POSIXRlimit } from './POSIXRlimit';

export class ContainerResourceConfig {
    /**
    * CPU period of the cpuset, determined by --cpus
    */
    'cpuPeriod'?: number;
    /**
    * CPU quota of the cpuset, determined by --cpus
    */
    'cpuQuota'?: number;
    /**
    * OOMScoreAdj adjusts the score used by the OOM killer to determine processes to kill for the container's process. Optional.
    */
    'oomScoreAdj'?: number;
    /**
    * Rlimits are POSIX rlimits to apply to the container. Optional.
    */
    'rLimits'?: Array<POSIXRlimit>;
    'resourceLimits'?: LinuxResources;
    /**
    * IO read rate limit per cgroup per device, bytes per second
    */
    'throttleReadBpsDevice'?: { [key: string]: LinuxThrottleDevice; };
    /**
    * IO read rate limit per cgroup per device, IO per second
    */
    'throttleReadIOPSDevice'?: { [key: string]: LinuxThrottleDevice; };
    /**
    * IO write rate limit per cgroup per device, bytes per second
    */
    'throttleWriteBpsDevice'?: { [key: string]: LinuxThrottleDevice; };
    /**
    * IO write rate limit per cgroup per device, IO per second
    */
    'throttleWriteIOPSDevice'?: { [key: string]: LinuxThrottleDevice; };
    /**
    * CgroupConf are key-value options passed into the container runtime that are used to configure cgroup v2. Optional.
    */
    'unified'?: { [key: string]: string; };
    /**
    * Weight per cgroup per device, can override BlkioWeight
    */
    'weightDevice'?: { [key: string]: LinuxWeightDevice; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'cpuPeriod',
            'baseName': 'cpu_period',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'cpuQuota',
            'baseName': 'cpu_quota',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'oomScoreAdj',
            'baseName': 'oom_score_adj',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'rLimits',
            'baseName': 'r_limits',
            'type': 'Array<POSIXRlimit>',
            'format': '',
        },
        {
            'name': 'resourceLimits',
            'baseName': 'resource_limits',
            'type': 'LinuxResources',
            'format': '',
        },
        {
            'name': 'throttleReadBpsDevice',
            'baseName': 'throttleReadBpsDevice',
            'type': '{ [key: string]: LinuxThrottleDevice; }',
            'format': '',
        },
        {
            'name': 'throttleReadIOPSDevice',
            'baseName': 'throttleReadIOPSDevice',
            'type': '{ [key: string]: LinuxThrottleDevice; }',
            'format': '',
        },
        {
            'name': 'throttleWriteBpsDevice',
            'baseName': 'throttleWriteBpsDevice',
            'type': '{ [key: string]: LinuxThrottleDevice; }',
            'format': '',
        },
        {
            'name': 'throttleWriteIOPSDevice',
            'baseName': 'throttleWriteIOPSDevice',
            'type': '{ [key: string]: LinuxThrottleDevice; }',
            'format': '',
        },
        {
            'name': 'unified',
            'baseName': 'unified',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'weightDevice',
            'baseName': 'weightDevice',
            'type': '{ [key: string]: LinuxWeightDevice; }',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return ContainerResourceConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

