/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class History {
    /**
    * Author is the author of the build point.
    */
    'author'?: string;
    /**
    * Comment is a custom message set when creating the layer.
    */
    'comment'?: string;
    /**
    * Created is the combined date and time at which the layer was created, formatted as defined by RFC 3339, section 5.6.
    */
    'created'?: Date;
    /**
    * CreatedBy is the command which created the layer.
    */
    'createdBy'?: string;
    /**
    * EmptyLayer is used to mark if the history item created a filesystem diff.
    */
    'emptyLayer'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'author',
            'baseName': 'author',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'comment',
            'baseName': 'comment',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'created',
            'baseName': 'created',
            'type': 'Date',
            'format': 'date-time',
        },
        {
            'name': 'createdBy',
            'baseName': 'created_by',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'emptyLayer',
            'baseName': 'empty_layer',
            'type': 'boolean',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return History.attributeTypeMap;
    }

    public constructor() {
    }
}

