/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AutoUserNsOptions } from './AutoUserNsOptions';
import type { IDMap } from './IDMap';

/**
* IDMappingOptions are used for specifying how ID mapping should be set up for a layer or container.
*/
export class IDMappingOptions {
    'autoUserNs'?: boolean;
    'autoUserNsOpts'?: AutoUserNsOptions;
    'gIDMap'?: Array<IDMap>;
    'hostGIDMapping'?: boolean;
    /**
    * UIDMap and GIDMap are used for setting up a layer's root filesystem for use inside of a user namespace where ID mapping is being used. If HostUIDMapping/HostGIDMapping is true, no mapping of the respective type will be used.  Otherwise, if UIDMap and/or GIDMap contain at least one mapping, one or both will be used.  By default, if neither of those conditions apply, if the layer has a parent layer, the parent layer's mapping will be used, and if it does not have a parent layer, the mapping which was passed to the Store object when it was initialized will be used.
    */
    'hostUIDMapping'?: boolean;
    'uIDMap'?: Array<IDMap>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'autoUserNs',
            'baseName': 'AutoUserNs',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'autoUserNsOpts',
            'baseName': 'AutoUserNsOpts',
            'type': 'AutoUserNsOptions',
            'format': '',
        },
        {
            'name': 'gIDMap',
            'baseName': 'GIDMap',
            'type': 'Array<IDMap>',
            'format': '',
        },
        {
            'name': 'hostGIDMapping',
            'baseName': 'HostGIDMapping',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'hostUIDMapping',
            'baseName': 'HostUIDMapping',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'uIDMap',
            'baseName': 'UIDMap',
            'type': 'Array<IDMap>',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return IDMappingOptions.attributeTypeMap;
    }

    public constructor() {
    }
}

