/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ImageConfig {
    /**
    * Cmd defines the default arguments to the entrypoint of the container.
    */
    'cmd'?: Array<string>;
    /**
    * Entrypoint defines a list of arguments to use as the command to execute when the container starts.
    */
    'entrypoint'?: Array<string>;
    /**
    * Env is a list of environment variables to be used in a container.
    */
    'env'?: Array<string>;
    /**
    * ExposedPorts a set of ports to expose from a container running this image.
    */
    'exposedPorts'?: { [key: string]: any; };
    /**
    * Labels contains arbitrary metadata for the container.
    */
    'labels'?: { [key: string]: string; };
    /**
    * StopSignal contains the system call signal that will be sent to the container to exit.
    */
    'stopSignal'?: string;
    /**
    * User defines the username or UID which the process in the container should run as.
    */
    'user'?: string;
    /**
    * Volumes is a set of directories describing where the process is likely write data specific to a container instance.
    */
    'volumes'?: { [key: string]: any; };
    /**
    * WorkingDir sets the current working directory of the entrypoint process in the container.
    */
    'workingDir'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'cmd',
            'baseName': 'Cmd',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'entrypoint',
            'baseName': 'Entrypoint',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'env',
            'baseName': 'Env',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'exposedPorts',
            'baseName': 'ExposedPorts',
            'type': '{ [key: string]: any; }',
            'format': '',
        },
        {
            'name': 'labels',
            'baseName': 'Labels',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'stopSignal',
            'baseName': 'StopSignal',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'user',
            'baseName': 'User',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'volumes',
            'baseName': 'Volumes',
            'type': '{ [key: string]: any; }',
            'format': '',
        },
        {
            'name': 'workingDir',
            'baseName': 'WorkingDir',
            'type': 'string',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return ImageConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

