/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InspectBlkioThrottleDevice } from './InspectBlkioThrottleDevice';
import type { InspectBlkioWeightDevice } from './InspectBlkioWeightDevice';
import type { InspectDevice } from './InspectDevice';
import type { InspectHostPort } from './InspectHostPort';
import type { InspectIDMappings } from './InspectIDMappings';
import type { InspectLogConfig } from './InspectLogConfig';
import type { InspectRestartPolicy } from './InspectRestartPolicy';
import type { InspectUlimit } from './InspectUlimit';

/**
* InspectContainerHostConfig holds information used when the container was created. It's very much a Docker-specific struct, retained (mostly) as-is for compatibility. We fill individual fields as best as we can, inferring as much as possible from the spec and container config. Some things cannot be inferred. These will be populated by spec annotations (if available). Field names are fixed for compatibility and cannot be changed. As such, silence lint warnings about them. nolint
*/
export class InspectContainerHostConfig {
    /**
    * AutoRemove is whether the container will be automatically removed on exiting. It is not handled directly within libpod and is stored in an annotation.
    */
    'autoRemove'?: boolean;
    /**
    * Binds contains an array of user-added mounts. Both volume mounts and named volumes are included. Tmpfs mounts are NOT included. In 'docker inspect' this is separated into 'Binds' and 'Mounts' based on how a mount was added. We do not make this distinction and do not include a Mounts field in inspect. Format: <src>:<destination>[:<comma-separated options>]
    */
    'binds'?: Array<string>;
    /**
    * BlkioDeviceReadBps is an array of I/O throttle parameters for individual device nodes. This specifically sets read rate cap in bytes per second for device nodes. As with BlkioWeightDevice, we pull the path from /sys/dev, and we don't guarantee the path will be identical to the original (though the node will be).
    */
    'blkioDeviceReadBps'?: Array<InspectBlkioThrottleDevice>;
    /**
    * BlkioDeviceReadIOps is an array of I/O throttle parameters for individual device nodes. This specifically sets the read rate cap in iops per second for device nodes. As with BlkioWeightDevice, we pull the path from /sys/dev, and we don't guarantee the path will be identical to the original (though the node will be).
    */
    'blkioDeviceReadIOps'?: Array<InspectBlkioThrottleDevice>;
    /**
    * BlkioDeviceWriteBps is an array of I/O throttle parameters for individual device nodes. this specifically sets write rate cap in bytes per second for device nodes. as with BlkioWeightDevice, we pull the path from /sys/dev, and we don't guarantee the path will be identical to the original (though the node will be).
    */
    'blkioDeviceWriteBps'?: Array<InspectBlkioThrottleDevice>;
    /**
    * BlkioDeviceWriteIOps is an array of I/O throttle parameters for individual device nodes. This specifically sets the write rate cap in iops per second for device nodes. As with BlkioWeightDevice, we pull the path from /sys/dev, and we don't guarantee the path will be identical to the original (though the node will be).
    */
    'blkioDeviceWriteIOps'?: Array<InspectBlkioThrottleDevice>;
    /**
    * BlkioWeight indicates the I/O resources allocated to the container. It is a relative weight in the scheduler for assigning I/O time versus other Cgroups.
    */
    'blkioWeight'?: number;
    /**
    * BlkioWeightDevice is an array of I/O resource priorities for individual device nodes. Unfortunately, the spec only stores the device's Major/Minor numbers and not the path, which is used here. Fortunately, the kernel provides an interface for retrieving the path of a given node by major:minor at /sys/dev/. However, the exact path in use may not be what was used in the original CLI invocation - though it is guaranteed that the device node will be the same, and using the given path will be functionally identical.
    */
    'blkioWeightDevice'?: Array<InspectBlkioWeightDevice>;
    /**
    * CapAdd is a list of capabilities added to the container. It is not directly stored by Libpod, and instead computed from the capabilities listed in the container's spec, compared against a set of default capabilities.
    */
    'capAdd'?: Array<string>;
    /**
    * CapDrop is a list of capabilities removed from the container. It is not directly stored by libpod, and instead computed from the capabilities listed in the container's spec, compared against a set of default capabilities.
    */
    'capDrop'?: Array<string>;
    /**
    * Cgroup contains the container's cgroup. It is presently not populated. TODO.
    */
    'cgroup'?: string;
    /**
    * CgroupConf is the configuration for cgroup v2.
    */
    'cgroupConf'?: { [key: string]: string; };
    /**
    * CgroupManager is the cgroup manager used by the container. At present, allowed values are either \"cgroupfs\" or \"systemd\".
    */
    'cgroupManager'?: string;
    /**
    * CgroupMode is the configuration of the container's cgroup namespace. Populated as follows: private - a cgroup namespace has been created host - No cgroup namespace created container:<id> - Using another container's cgroup namespace ns:<path> - A path to a cgroup namespace has been specified
    */
    'cgroupMode'?: string;
    /**
    * CgroupParent is the Cgroup parent of the container. Only set if not default.
    */
    'cgroupParent'?: string;
    /**
    * Cgroups contains the container's Cgroup mode. Allowed values are \"default\" (container is creating Cgroups) and \"disabled\" (container is not creating Cgroups). This is Libpod-specific and not included in `docker inspect`.
    */
    'cgroups'?: string;
    /**
    * ConsoleSize is an array of 2 integers showing the size of the container's console. It is only set if the container is creating a terminal. TODO.
    */
    'consoleSize'?: Array<number>;
    /**
    * ContainerIDFile is a file created during container creation to hold the ID of the created container. This is not handled within libpod and is stored in an annotation.
    */
    'containerIDFile'?: string;
    /**
    * CpuCount is Windows-only and not presently implemented.
    */
    'cpuCount'?: number;
    /**
    * CpuPercent is Windows-only and not presently implemented.
    */
    'cpuPercent'?: number;
    /**
    * CpuPeriod is the length of a CPU period in microseconds. It relates directly to CpuQuota.
    */
    'cpuPeriod'?: number;
    /**
    * CpuPeriod is the amount of time (in microseconds) that a container can use the CPU in every CpuPeriod.
    */
    'cpuQuota'?: number;
    /**
    * CpuRealtimePeriod is the length of time (in microseconds) of the CPU realtime period. If set to 0, no time will be allocated to realtime tasks.
    */
    'cpuRealtimePeriod'?: number;
    /**
    * CpuRealtimeRuntime is the length of time (in microseconds) allocated for realtime tasks within every CpuRealtimePeriod.
    */
    'cpuRealtimeRuntime'?: number;
    /**
    * CpuShares indicates the CPU resources allocated to the container. It is a relative weight in the scheduler for assigning CPU time versus other Cgroups.
    */
    'cpuShares'?: number;
    /**
    * CpusetCpus is the is the set of CPUs that the container will execute on. Formatted as `0-3` or `0,2`. Default (if unset) is all CPUs.
    */
    'cpusetCpus'?: string;
    /**
    * CpusetMems is the set of memory nodes the container will use. Formatted as `0-3` or `0,2`. Default (if unset) is all memory nodes.
    */
    'cpusetMems'?: string;
    /**
    * Devices is a list of device nodes that will be added to the container. These are stored in the OCI spec only as type, major, minor while we display the host path. We convert this with /sys/dev, but we cannot guarantee that the host path will be identical - only that the actual device will be.
    */
    'devices'?: Array<InspectDevice>;
    /**
    * DiskQuota is the maximum amount of disk space the container may use (in bytes). Presently not populated. TODO.
    */
    'diskQuota'?: number;
    /**
    * Dns is a list of DNS nameservers that will be added to the container's resolv.conf
    */
    'dns'?: Array<string>;
    /**
    * DnsOptions is a list of DNS options that will be set in the container's resolv.conf
    */
    'dnsOptions'?: Array<string>;
    /**
    * DnsSearch is a list of DNS search domains that will be set in the container's resolv.conf
    */
    'dnsSearch'?: Array<string>;
    /**
    * ExtraHosts contains hosts that will be aded to the container's etc/hosts.
    */
    'extraHosts'?: Array<string>;
    /**
    * GroupAdd contains groups that the user inside the container will be added to.
    */
    'groupAdd'?: Array<string>;
    'iDMappings'?: InspectIDMappings;
    /**
    * IOMaximumBandwidth is Windows-only and not presently implemented.
    */
    'iOMaximumBandwidth'?: number;
    /**
    * IOMaximumIOps is Windows-only and not presently implemented.
    */
    'iOMaximumIOps'?: number;
    /**
    * Init indicates whether the container has an init mounted into it.
    */
    'init'?: boolean;
    /**
    * IpcMode represents the configuration of the container's IPC namespace. Populated as follows: \"\" (empty string) - Default, an IPC namespace will be created host - No IPC namespace created container:<id> - Using another container's IPC namespace ns:<path> - A path to an IPC namespace has been specified
    */
    'ipcMode'?: string;
    /**
    * Isolation is presently unused and provided solely for Docker compatibility.
    */
    'isolation'?: string;
    /**
    * KernelMemory is the maximum amount of memory the kernel will devote to the container.
    */
    'kernelMemory'?: number;
    /**
    * Links is unused, and provided purely for Docker compatibility.
    */
    'links'?: Array<string>;
    'logConfig'?: InspectLogConfig;
    /**
    * Memory indicates the memory resources allocated to the container. This is the limit (in bytes) of RAM the container may use.
    */
    'memory'?: number;
    /**
    * MemoryReservation is the reservation (soft limit) of memory available to the container. Soft limits are warnings only and can be exceeded.
    */
    'memoryReservation'?: number;
    /**
    * MemorySwap is the total limit for all memory available to the container, including swap. 0 indicates that there is no limit to the amount of memory available.
    */
    'memorySwap'?: number;
    /**
    * MemorySwappiness is the willingness of the kernel to page container memory to swap. It is an integer from 0 to 100, with low numbers being more likely to be put into swap. 1, the default, will not set swappiness and use the system defaults.
    */
    'memorySwappiness'?: number;
    /**
    * NanoCpus indicates number of CPUs allocated to the container. It is an integer where one full CPU is indicated by 1000000000 (one billion). Thus, 2.5 CPUs (fractional portions of CPUs are allowed) would be 2500000000 (2.5 billion). In 'docker inspect' this is set exclusively of two further options in the output (CpuPeriod and CpuQuota) which are both used to implement this functionality. We can't distinguish here, so if CpuQuota is set to the default of 100000, we will set both CpuQuota, CpuPeriod, and NanoCpus. If CpuQuota is not the default, we will not set NanoCpus.
    */
    'nanoCpus'?: number;
    /**
    * NetworkMode is the configuration of the container's network namespace. Populated as follows: default - A network namespace is being created and configured via CNI none - A network namespace is being created, not configured via CNI host - No network namespace created container:<id> - Using another container's network namespace ns:<path> - A path to a network namespace has been specified
    */
    'networkMode'?: string;
    /**
    * OomKillDisable indicates whether the kernel OOM killer is disabled for the container.
    */
    'oomKillDisable'?: boolean;
    /**
    * OOMScoreAdj is an adjustment that will be made to the container's OOM score.
    */
    'oomScoreAdj'?: number;
    /**
    * PidMode represents the configuration of the container's PID namespace. Populated as follows: \"\" (empty string) - Default, a PID namespace will be created host - No PID namespace created container:<id> - Using another container's PID namespace ns:<path> - A path to a PID namespace has been specified
    */
    'pidMode'?: string;
    /**
    * PidsLimit is the maximum number of PIDs what may be created within the container. 0, the default, indicates no limit.
    */
    'pidsLimit'?: number;
    /**
    * PortBindings contains the container's port bindings. It is formatted as map[string][]InspectHostPort. The string key here is formatted as <integer port number>/<protocol> and represents the container port. A single container port may be bound to multiple host ports (on different IPs).
    */
    'portBindings'?: { [key: string]: Array<InspectHostPort>; };
    /**
    * Privileged indicates whether the container is running with elevated privileges. This has a very specific meaning in the Docker sense, so it's very difficult to decode from the spec and config, and so is stored as an annotation.
    */
    'privileged'?: boolean;
    /**
    * PublishAllPorts indicates whether image ports are being published. This is not directly stored in libpod and is saved as an annotation.
    */
    'publishAllPorts'?: boolean;
    /**
    * ReadonlyRootfs is whether the container will be mounted read-only.
    */
    'readonlyRootfs'?: boolean;
    'restartPolicy'?: InspectRestartPolicy;
    /**
    * Runtime is provided purely for Docker compatibility. It is set unconditionally to \"oci\" as Podman does not presently support non-OCI runtimes.
    */
    'runtime'?: string;
    /**
    * SecurityOpt is a list of security-related options that are set in the container.
    */
    'securityOpt'?: Array<string>;
    'shmSize'?: number;
    /**
    * Tmpfs is a list of tmpfs filesystems that will be mounted into the container. It is a map of destination path to options for the mount.
    */
    'tmpfs'?: { [key: string]: string; };
    /**
    * UTSMode represents the configuration of the container's UID namespace. Populated as follows: \"\" (empty string) - Default, a UTS namespace will be created host - no UTS namespace created container:<id> - Using another container's UTS namespace ns:<path> - A path to a UTS namespace has been specified
    */
    'uTSMode'?: string;
    /**
    * Ulimits is a set of ulimits that will be set within the container.
    */
    'ulimits'?: Array<InspectUlimit>;
    /**
    * UsernsMode represents the configuration of the container's user namespace. When running rootless, a user namespace is created outside of libpod to allow some privileged operations. This will not be reflected here. Populated as follows: \"\" (empty string) - No user namespace will be created private - The container will be run in a user namespace container:<id> - Using another container's user namespace ns:<path> - A path to a user namespace has been specified TODO Rootless has an additional 'keep-id' option, presently not reflected here.
    */
    'usernsMode'?: string;
    /**
    * VolumeDriver is presently unused and is retained for Docker compatibility.
    */
    'volumeDriver'?: string;
    /**
    * VolumesFrom is a list of containers which this container uses volumes from. This is not handled directly within libpod and is stored in an annotation. It is formatted as an array of container names and IDs.
    */
    'volumesFrom'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'autoRemove',
            'baseName': 'AutoRemove',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'binds',
            'baseName': 'Binds',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'blkioDeviceReadBps',
            'baseName': 'BlkioDeviceReadBps',
            'type': 'Array<InspectBlkioThrottleDevice>',
            'format': '',
        },
        {
            'name': 'blkioDeviceReadIOps',
            'baseName': 'BlkioDeviceReadIOps',
            'type': 'Array<InspectBlkioThrottleDevice>',
            'format': '',
        },
        {
            'name': 'blkioDeviceWriteBps',
            'baseName': 'BlkioDeviceWriteBps',
            'type': 'Array<InspectBlkioThrottleDevice>',
            'format': '',
        },
        {
            'name': 'blkioDeviceWriteIOps',
            'baseName': 'BlkioDeviceWriteIOps',
            'type': 'Array<InspectBlkioThrottleDevice>',
            'format': '',
        },
        {
            'name': 'blkioWeight',
            'baseName': 'BlkioWeight',
            'type': 'number',
            'format': 'uint16',
        },
        {
            'name': 'blkioWeightDevice',
            'baseName': 'BlkioWeightDevice',
            'type': 'Array<InspectBlkioWeightDevice>',
            'format': '',
        },
        {
            'name': 'capAdd',
            'baseName': 'CapAdd',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'capDrop',
            'baseName': 'CapDrop',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'cgroup',
            'baseName': 'Cgroup',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'cgroupConf',
            'baseName': 'CgroupConf',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'cgroupManager',
            'baseName': 'CgroupManager',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'cgroupMode',
            'baseName': 'CgroupMode',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'cgroupParent',
            'baseName': 'CgroupParent',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'cgroups',
            'baseName': 'Cgroups',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'consoleSize',
            'baseName': 'ConsoleSize',
            'type': 'Array<number>',
            'format': 'uint64',
        },
        {
            'name': 'containerIDFile',
            'baseName': 'ContainerIDFile',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'cpuCount',
            'baseName': 'CpuCount',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'cpuPercent',
            'baseName': 'CpuPercent',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'cpuPeriod',
            'baseName': 'CpuPeriod',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'cpuQuota',
            'baseName': 'CpuQuota',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'cpuRealtimePeriod',
            'baseName': 'CpuRealtimePeriod',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'cpuRealtimeRuntime',
            'baseName': 'CpuRealtimeRuntime',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'cpuShares',
            'baseName': 'CpuShares',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'cpusetCpus',
            'baseName': 'CpusetCpus',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'cpusetMems',
            'baseName': 'CpusetMems',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'devices',
            'baseName': 'Devices',
            'type': 'Array<InspectDevice>',
            'format': '',
        },
        {
            'name': 'diskQuota',
            'baseName': 'DiskQuota',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'dns',
            'baseName': 'Dns',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'dnsOptions',
            'baseName': 'DnsOptions',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'dnsSearch',
            'baseName': 'DnsSearch',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'extraHosts',
            'baseName': 'ExtraHosts',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'groupAdd',
            'baseName': 'GroupAdd',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'iDMappings',
            'baseName': 'IDMappings',
            'type': 'InspectIDMappings',
            'format': '',
        },
        {
            'name': 'iOMaximumBandwidth',
            'baseName': 'IOMaximumBandwidth',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'iOMaximumIOps',
            'baseName': 'IOMaximumIOps',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'init',
            'baseName': 'Init',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'ipcMode',
            'baseName': 'IpcMode',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'isolation',
            'baseName': 'Isolation',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'kernelMemory',
            'baseName': 'KernelMemory',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'links',
            'baseName': 'Links',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'logConfig',
            'baseName': 'LogConfig',
            'type': 'InspectLogConfig',
            'format': '',
        },
        {
            'name': 'memory',
            'baseName': 'Memory',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'memoryReservation',
            'baseName': 'MemoryReservation',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'memorySwap',
            'baseName': 'MemorySwap',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'memorySwappiness',
            'baseName': 'MemorySwappiness',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'nanoCpus',
            'baseName': 'NanoCpus',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'networkMode',
            'baseName': 'NetworkMode',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'oomKillDisable',
            'baseName': 'OomKillDisable',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'oomScoreAdj',
            'baseName': 'OomScoreAdj',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'pidMode',
            'baseName': 'PidMode',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'pidsLimit',
            'baseName': 'PidsLimit',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'portBindings',
            'baseName': 'PortBindings',
            'type': '{ [key: string]: Array<InspectHostPort>; }',
            'format': '',
        },
        {
            'name': 'privileged',
            'baseName': 'Privileged',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'publishAllPorts',
            'baseName': 'PublishAllPorts',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'readonlyRootfs',
            'baseName': 'ReadonlyRootfs',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'restartPolicy',
            'baseName': 'RestartPolicy',
            'type': 'InspectRestartPolicy',
            'format': '',
        },
        {
            'name': 'runtime',
            'baseName': 'Runtime',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'securityOpt',
            'baseName': 'SecurityOpt',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'shmSize',
            'baseName': 'ShmSize',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'tmpfs',
            'baseName': 'Tmpfs',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'uTSMode',
            'baseName': 'UTSMode',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'ulimits',
            'baseName': 'Ulimits',
            'type': 'Array<InspectUlimit>',
            'format': '',
        },
        {
            'name': 'usernsMode',
            'baseName': 'UsernsMode',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'volumeDriver',
            'baseName': 'VolumeDriver',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'volumesFrom',
            'baseName': 'VolumesFrom',
            'type': 'Array<string>',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return InspectContainerHostConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

