/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* LinuxCPU for Linux cgroup 'cpu' resource management
*/
export class LinuxCPU {
    /**
    * CPUs to use within the cpuset. Default is to use any CPU available.
    */
    'cpus'?: string;
    /**
    * List of memory nodes in the cpuset. Default is to use any available memory node.
    */
    'mems'?: string;
    /**
    * CPU period to be used for hardcapping (in usecs).
    */
    'period'?: number;
    /**
    * CPU hardcap limit (in usecs). Allowed cpu time in a given period.
    */
    'quota'?: number;
    /**
    * CPU period to be used for realtime scheduling (in usecs).
    */
    'realtimePeriod'?: number;
    /**
    * How much time realtime scheduling may use (in usecs).
    */
    'realtimeRuntime'?: number;
    /**
    * CPU shares (relative weight (ratio) vs. other cgroups with cpu shares).
    */
    'shares'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'cpus',
            'baseName': 'cpus',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'mems',
            'baseName': 'mems',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'period',
            'baseName': 'period',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'quota',
            'baseName': 'quota',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'realtimePeriod',
            'baseName': 'realtimePeriod',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'realtimeRuntime',
            'baseName': 'realtimeRuntime',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'shares',
            'baseName': 'shares',
            'type': 'number',
            'format': 'uint64',
        }    ];

    static getAttributeTypeMap() {
        return LinuxCPU.attributeTypeMap;
    }

    public constructor() {
    }
}

