/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* LinuxDevice represents the mknod information for a Linux special device file
*/
export class LinuxDevice {
    /**
    * The bits have the same definition on all systems, so that information about files can be moved from one system to another portably. Not all bits apply to all systems. The only required bit is ModeDir for directories.
    */
    'fileMode'?: number;
    /**
    * Gid of the device.
    */
    'gid'?: number;
    /**
    * Major is the device's major number.
    */
    'major'?: number;
    /**
    * Minor is the device's minor number.
    */
    'minor'?: number;
    /**
    * Path to the device.
    */
    'path'?: string;
    /**
    * Device type, block, char, etc.
    */
    'type'?: string;
    /**
    * UID of the device.
    */
    'uid'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'fileMode',
            'baseName': 'fileMode',
            'type': 'number',
            'format': 'uint32',
        },
        {
            'name': 'gid',
            'baseName': 'gid',
            'type': 'number',
            'format': 'uint32',
        },
        {
            'name': 'major',
            'baseName': 'major',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'minor',
            'baseName': 'minor',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'path',
            'baseName': 'path',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'type',
            'baseName': 'type',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'uid',
            'baseName': 'uid',
            'type': 'number',
            'format': 'uint32',
        }    ];

    static getAttributeTypeMap() {
        return LinuxDevice.attributeTypeMap;
    }

    public constructor() {
    }
}

