/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConfigReference } from './ConfigReference';
import type { IPAM } from './IPAM';

export class NetworkCreateRequest {
    'attachable'?: boolean;
    /**
    * Check for networks with duplicate names. Network is primarily keyed based on a random ID and not on the name. Network name is strictly a user-friendly alias to the network which is uniquely identified using ID. And there is no guaranteed way to check for duplicates. Option CheckDuplicate is there to provide a best effort checking of any networks which has the same name but it is not guaranteed to catch all name collisions.
    */
    'checkDuplicate'?: boolean;
    'configFrom'?: ConfigReference;
    'configOnly'?: boolean;
    'driver'?: string;
    'enableIPv6'?: boolean;
    'IPAM'?: IPAM;
    'ingress'?: boolean;
    'internal'?: boolean;
    'labels'?: { [key: string]: string; };
    'name'?: string;
    'options'?: { [key: string]: string; };
    'scope'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'attachable',
            'baseName': 'Attachable',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'checkDuplicate',
            'baseName': 'CheckDuplicate',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'configFrom',
            'baseName': 'ConfigFrom',
            'type': 'ConfigReference',
            'format': '',
        },
        {
            'name': 'configOnly',
            'baseName': 'ConfigOnly',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'driver',
            'baseName': 'Driver',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'enableIPv6',
            'baseName': 'EnableIPv6',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'IPAM',
            'baseName': 'IPAM',
            'type': 'IPAM',
            'format': '',
        },
        {
            'name': 'ingress',
            'baseName': 'Ingress',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'internal',
            'baseName': 'Internal',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'labels',
            'baseName': 'Labels',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'name',
            'baseName': 'Name',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'options',
            'baseName': 'Options',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'scope',
            'baseName': 'Scope',
            'type': 'string',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return NetworkCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

