/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Subnet } from './Subnet';

export class Network {
    /**
    * Created contains the timestamp when this network was created.
    */
    'created'?: Date;
    /**
    * DNSEnabled is whether name resolution is active for container on this Network.
    */
    'dnsEnabled'?: boolean;
    /**
    * Driver for this Network, e.g. bridge, macvlan...
    */
    'driver'?: string;
    /**
    * ID of the Network.
    */
    'id'?: string;
    /**
    * Internal is whether the Network should not have external routes to public or other Networks.
    */
    'internal'?: boolean;
    /**
    * IPAMOptions contains options used for the ip assignment.
    */
    'ipamOptions'?: { [key: string]: string; };
    /**
    * IPv6Enabled if set to true an ipv6 subnet should be created for this net.
    */
    'ipv6Enabled'?: boolean;
    /**
    * Labels is a set of key-value labels that have been applied to the Network.
    */
    'labels'?: { [key: string]: string; };
    /**
    * Name of the Network.
    */
    'name'?: string;
    /**
    * NetworkInterface is the network interface name on the host.
    */
    'networkInterface'?: string;
    /**
    * Options is a set of key-value options that have been applied to the Network.
    */
    'options'?: { [key: string]: string; };
    /**
    * Subnets to use for this network.
    */
    'subnets'?: Array<Subnet>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'created',
            'baseName': 'created',
            'type': 'Date',
            'format': 'date-time',
        },
        {
            'name': 'dnsEnabled',
            'baseName': 'dns_enabled',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'driver',
            'baseName': 'driver',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'id',
            'baseName': 'id',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'internal',
            'baseName': 'internal',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'ipamOptions',
            'baseName': 'ipam_options',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'ipv6Enabled',
            'baseName': 'ipv6_enabled',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'labels',
            'baseName': 'labels',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'name',
            'baseName': 'name',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'networkInterface',
            'baseName': 'network_interface',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'options',
            'baseName': 'options',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'subnets',
            'baseName': 'subnets',
            'type': 'Array<Subnet>',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return Network.attributeTypeMap;
    }

    public constructor() {
    }
}

