/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Platform {
    /**
    * Architecture field specifies the CPU architecture, for example `amd64` or `ppc64`.
    */
    'architecture'?: string;
    /**
    * OS specifies the operating system, for example `linux` or `windows`.
    */
    'os'?: string;
    /**
    * OSFeatures is an optional field specifying an array of strings, each listing a required OS feature (for example on Windows `win32k`).
    */
    'osFeatures'?: Array<string>;
    /**
    * OSVersion is an optional field specifying the operating system version, for example on Windows `10.0.14393.1066`.
    */
    'osVersion'?: string;
    /**
    * Variant is an optional field specifying a variant of the CPU, for example `v7` to specify ARMv7 when architecture is `arm`.
    */
    'variant'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'architecture',
            'baseName': 'architecture',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'os',
            'baseName': 'os',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'osFeatures',
            'baseName': 'os.features',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'osVersion',
            'baseName': 'os.version',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'variant',
            'baseName': 'variant',
            'type': 'string',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return Platform.attributeTypeMap;
    }

    public constructor() {
    }
}

