/**
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v4.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v4.0.0/libpod/images/json' | jq
 *
 * OpenAPI spec version: 4.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IDMappingOptions } from './IDMappingOptions';
import type { ImageVolume } from './ImageVolume';
import type { LinuxResources } from './LinuxResources';
import type { LinuxThrottleDevice } from './LinuxThrottleDevice';
import type { Mount } from './Mount';
import type { NamedVolume } from './NamedVolume';
import type { Namespace } from './Namespace';
import type { OverlayVolume } from './OverlayVolume';
import type { PerNetworkOptions } from './PerNetworkOptions';
import type { PortMapping } from './PortMapping';

/**
* PodSpecGenerator describes options to create a pod
*/
export class PodSpecGenerator {
    /**
    * Map of networks names to ids the container should join to. You can request additional settings for each network, you can set network aliases, static ips, static mac address  and the network interface name for this container on the specific network. If the map is empty and the bridge network mode is set the container will be joined to the default network.
    */
    'networks'?: { [key: string]: PerNetworkOptions; };
    /**
    * CgroupParent is the parent for the Cgroup that the pod will create. This pod cgroup will, in turn, be the default cgroup parent for all containers in the pod. Optional.
    */
    'cgroupParent'?: string;
    /**
    * CNINetworks is a list of CNI networks to join the container to. If this list is empty, the default CNI network will be joined instead. If at least one entry is present, we will not join the default network (unless it is part of this list). Only available if NetNS is set to bridge. Optional. Deprecated: as of podman 4.0 use \"Networks\" instead.
    */
    'cniNetworks'?: Array<string>;
    /**
    * CPU period of the cpuset, determined by --cpus
    */
    'cpuPeriod'?: number;
    /**
    * CPU quota of the cpuset, determined by --cpus
    */
    'cpuQuota'?: number;
    /**
    * DNSOption is a set of DNS options that will be used in the infra container's resolv.conf, which will, by default, be shared with all containers in the pod. Conflicts with NoInfra=true. Optional.
    */
    'dnsOption'?: Array<string>;
    /**
    * DNSSearch is a set of DNS search domains that will be used in the infra container's resolv.conf, which will, by default, be shared with all containers in the pod. If not provided, DNS search domains from the host's resolv.conf will be used. Conflicts with NoInfra=true. Optional.
    */
    'dnsSearch'?: Array<string>;
    /**
    * DNSServer is a set of DNS servers that will be used in the infra container's resolv.conf, which will, by default, be shared with all containers in the pod. If not provided, the host's DNS servers will be used, unless the only server set is a localhost address. As the container cannot connect to the host's localhost, a default server will instead be set. Conflicts with NoInfra=true. Optional.
    */
    'dnsServer'?: Array<Array<number>>;
    /**
    * HostAdd is a set of hosts that will be added to the infra container's etc/hosts that will, by default, be shared with all containers in the pod. Conflicts with NoInfra=true and NoManageHosts. Optional.
    */
    'hostadd'?: Array<string>;
    /**
    * Hostname is the pod's hostname. If not set, the name of the pod will be used (if a name was not provided here, the name auto-generated for the pod will be used). This will be used by the infra container and all containers in the pod as long as the UTS namespace is shared. Optional.
    */
    'hostname'?: string;
    'idmappings'?: IDMappingOptions;
    /**
    * Image volumes bind-mount a container-image mount into the pod's infra container. Optional.
    */
    'imageVolumes'?: Array<ImageVolume>;
    /**
    * InfraCommand sets the command that will be used to start the infra container. If not set, the default set in the Libpod configuration file will be used. Conflicts with NoInfra=true. Optional.
    */
    'infraCommand'?: Array<string>;
    /**
    * InfraConmonPidFile is a custom path to store the infra container's conmon PID.
    */
    'infraConmonPidFile'?: string;
    /**
    * InfraImage is the image that will be used for the infra container. If not set, the default set in the Libpod configuration file will be used. Conflicts with NoInfra=true. Optional.
    */
    'infraImage'?: string;
    /**
    * InfraName is the name that will be used for the infra container. If not set, the default set in the Libpod configuration file will be used. Conflicts with NoInfra=true. Optional.
    */
    'infraName'?: string;
    /**
    * Labels are key-value pairs that are used to add metadata to pods. Optional.
    */
    'labels'?: { [key: string]: string; };
    /**
    * Mounts are mounts that will be added to the pod. These will supersede Image Volumes and VolumesFrom volumes where there are conflicts. Optional.
    */
    'mounts'?: Array<Mount>;
    /**
    * Name is the name of the pod. If not provided, a name will be generated when the pod is created. Optional.
    */
    'name'?: string;
    'netns'?: Namespace;
    /**
    * NetworkOptions are additional options for each network Optional.
    */
    'networkOptions'?: { [key: string]: Array<string>; };
    /**
    * NoInfra tells the pod not to create an infra container. If this is done, many networking-related options will become unavailable. Conflicts with setting any options in PodNetworkConfig, and the InfraCommand and InfraImages in this struct. Optional.
    */
    'noInfra'?: boolean;
    /**
    * NoManageHosts indicates that /etc/hosts should not be managed by the pod. Instead, each container will create a separate /etc/hosts as they would if not in a pod. Conflicts with HostAdd.
    */
    'noManageHosts'?: boolean;
    /**
    * NoManageResolvConf indicates that /etc/resolv.conf should not be managed by the pod. Instead, each container will create and manage a separate resolv.conf as if they had not joined a pod. Conflicts with NoInfra=true and DNSServer, DNSSearch, DNSOption. Optional.
    */
    'noManageResolvConf'?: boolean;
    /**
    * Overlay volumes are named volumes that will be added to the pod. Optional.
    */
    'overlayVolumes'?: Array<OverlayVolume>;
    'pidns'?: Namespace;
    'podCreateCommand'?: Array<string>;
    /**
    * Devices contains user specified Devices to be added to the Pod
    */
    'podDevices'?: Array<string>;
    /**
    * PortMappings is a set of ports to map into the infra container. As, by default, containers share their network with the infra container, this will forward the ports to the entire pod. Only available if NetNS is set to Bridge or Slirp. Optional.
    */
    'portmappings'?: Array<PortMapping>;
    'resourceLimits'?: LinuxResources;
    'securityOpt'?: Array<string>;
    /**
    * PodCreateCommand is the command used to create this pod. This will be shown in the output of Inspect() on the pod, and may also be used by some tools that wish to recreate the pod (e.g. `podman generate systemd --new`). Optional. ShareParent determines if all containers in the pod will share the pod's cgroup as the cgroup parent
    */
    'shareParent'?: boolean;
    /**
    * SharedNamespaces instructs the pod to share a set of namespaces. Shared namespaces will be joined (by default) by every container which joins the pod. If not set and NoInfra is false, the pod will set a default set of namespaces to share. Conflicts with NoInfra=true. Optional.
    */
    'sharedNamespaces'?: Array<string>;
    /**
    * Sysctl sets kernel parameters for the pod
    */
    'sysctl'?: { [key: string]: string; };
    /**
    * ThrottleReadBpsDevice contains the rate at which the devices in the pod can be read from/accessed
    */
    'throttleReadBpsDevice'?: { [key: string]: LinuxThrottleDevice; };
    'userns'?: Namespace;
    /**
    * Volumes are named volumes that will be added to the pod. These will supersede Image Volumes and VolumesFrom  volumes where there are conflicts. Optional.
    */
    'volumes'?: Array<NamedVolume>;
    /**
    * VolumesFrom is a set of containers whose volumes will be added to this pod. The name or ID of the container must be provided, and may optionally be followed by a : and then one or more comma-separated options. Valid options are 'ro', 'rw', and 'z'. Options will be used for all volumes sourced from the container.
    */
    'volumesFrom'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            'name': 'networks',
            'baseName': 'Networks',
            'type': '{ [key: string]: PerNetworkOptions; }',
            'format': '',
        },
        {
            'name': 'cgroupParent',
            'baseName': 'cgroup_parent',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'cniNetworks',
            'baseName': 'cni_networks',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'cpuPeriod',
            'baseName': 'cpu_period',
            'type': 'number',
            'format': 'uint64',
        },
        {
            'name': 'cpuQuota',
            'baseName': 'cpu_quota',
            'type': 'number',
            'format': 'int64',
        },
        {
            'name': 'dnsOption',
            'baseName': 'dns_option',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'dnsSearch',
            'baseName': 'dns_search',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'dnsServer',
            'baseName': 'dns_server',
            'type': 'Array<Array<number>>',
            'format': 'uint8',
        },
        {
            'name': 'hostadd',
            'baseName': 'hostadd',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'hostname',
            'baseName': 'hostname',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'idmappings',
            'baseName': 'idmappings',
            'type': 'IDMappingOptions',
            'format': '',
        },
        {
            'name': 'imageVolumes',
            'baseName': 'image_volumes',
            'type': 'Array<ImageVolume>',
            'format': '',
        },
        {
            'name': 'infraCommand',
            'baseName': 'infra_command',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'infraConmonPidFile',
            'baseName': 'infra_conmon_pid_file',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'infraImage',
            'baseName': 'infra_image',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'infraName',
            'baseName': 'infra_name',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'labels',
            'baseName': 'labels',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'mounts',
            'baseName': 'mounts',
            'type': 'Array<Mount>',
            'format': '',
        },
        {
            'name': 'name',
            'baseName': 'name',
            'type': 'string',
            'format': '',
        },
        {
            'name': 'netns',
            'baseName': 'netns',
            'type': 'Namespace',
            'format': '',
        },
        {
            'name': 'networkOptions',
            'baseName': 'network_options',
            'type': '{ [key: string]: Array<string>; }',
            'format': '',
        },
        {
            'name': 'noInfra',
            'baseName': 'no_infra',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'noManageHosts',
            'baseName': 'no_manage_hosts',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'noManageResolvConf',
            'baseName': 'no_manage_resolv_conf',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'overlayVolumes',
            'baseName': 'overlay_volumes',
            'type': 'Array<OverlayVolume>',
            'format': '',
        },
        {
            'name': 'pidns',
            'baseName': 'pidns',
            'type': 'Namespace',
            'format': '',
        },
        {
            'name': 'podCreateCommand',
            'baseName': 'pod_create_command',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'podDevices',
            'baseName': 'pod_devices',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'portmappings',
            'baseName': 'portmappings',
            'type': 'Array<PortMapping>',
            'format': '',
        },
        {
            'name': 'resourceLimits',
            'baseName': 'resource_limits',
            'type': 'LinuxResources',
            'format': '',
        },
        {
            'name': 'securityOpt',
            'baseName': 'security_opt',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'shareParent',
            'baseName': 'share_parent',
            'type': 'boolean',
            'format': '',
        },
        {
            'name': 'sharedNamespaces',
            'baseName': 'shared_namespaces',
            'type': 'Array<string>',
            'format': '',
        },
        {
            'name': 'sysctl',
            'baseName': 'sysctl',
            'type': '{ [key: string]: string; }',
            'format': '',
        },
        {
            'name': 'throttleReadBpsDevice',
            'baseName': 'throttleReadBpsDevice',
            'type': '{ [key: string]: LinuxThrottleDevice; }',
            'format': '',
        },
        {
            'name': 'userns',
            'baseName': 'userns',
            'type': 'Namespace',
            'format': '',
        },
        {
            'name': 'volumes',
            'baseName': 'volumes',
            'type': 'Array<NamedVolume>',
            'format': '',
        },
        {
            'name': 'volumesFrom',
            'baseName': 'volumes_from',
            'type': 'Array<string>',
            'format': '',
        }    ];

    static getAttributeTypeMap() {
        return PodSpecGenerator.attributeTypeMap;
    }

    public constructor() {
    }
}

